import React,{useEffect,useState} from 'react';
const API='/api'; type User={id:string,name:string,role:'doctor'|'patient'}; const games=['Communication Choices','Story Builder','Daily Steps','Feelings Explorer'];
async function call(path:string,token:string,method='GET',body?:any){const r=await fetch(API+path,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');return data}
export default function App(){const [token,setToken]=useState(localStorage.getItem('token')||'');const [user,setUser]=useState<User|null>(JSON.parse(localStorage.getItem('user')||'null'));const [email,setEmail]=useState('doctor@neuplay.demo'),[password,setPassword]=useState('doctor123'),[loginRole,setLoginRole]=useState<'doctor'|'patient'>('doctor'),[error,setError]=useState('');const [patients,setPatients]=useState<any[]>([]),[patient,setPatient]=useState<any>(null),[assignments,setAssignments]=useState<any[]>([]);const [tab,setTab]=useState('Overview'),[suggestions,setSuggestions]=useState<any[]>([]),[game,setGame]=useState<any>(null),[session,setSession]=useState<any>(null),[remaining,setRemaining]=useState(0),[demo,setDemo]=useState(false),[toast,setToast]=useState(''),[paused,setPaused]=useState(false),[newPatient,setNewPatient]=useState(false),[patientForm,setPatientForm]=useState<any>({name:'',email:'',password:'',ageBand:'6–9',interests:'',communication:'',sensory:'',goals:''});
function logout(){localStorage.clear();setToken('');setUser(null);setSession(null)}
async function login(e:any){e.preventDefault();setError('');try{const d=await fetch(API+'/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})}).then(r=>r.json());if(!d.token)throw Error(d.error);if(d.user.role!==loginRole)throw Error(`This account is for ${d.user.role} login. Choose the matching login tab.`);localStorage.setItem('token',d.token);localStorage.setItem('user',JSON.stringify(d.user));setToken(d.token);setUser(d.user)}catch(x:any){setError(x.message)}}
async function loadDoctor(){try{const settings=await call('/settings',token);setDemo(settings.demoTimer);const p=await call('/patients',token);setPatients(p);setPatient((old:any)=>p.find((x:any)=>x.id===old?.id)||p[0])}catch(e:any){setError(e.message)}} async function loadPatient(){try{const d=await call('/my-assignments',token);setAssignments(d.items);setDemo(d.demoTimer)}catch(e:any){setError(e.message)}}
useEffect(()=>{if(user?.role==='doctor')loadDoctor();if(user?.role==='patient')loadPatient()},[token,user?.role]);useEffect(()=>{if(user?.role!=='doctor'||!token)return;const t=setInterval(loadDoctor,5000);return()=>clearInterval(t)},[token,user?.role]);useEffect(()=>{if(!session)return;const t=setInterval(async()=>{try{const s=await call(`/sessions/${session.id}/status`,token);setRemaining(s.remaining);setPaused(!!s.session.pausedAt);if(s.expired)finish('time_limit',false)}catch{}},1000);return()=>clearInterval(t)},[session?.id]);
async function getSuggestions(){try{const d=await call('/suggest',token,'POST',{goals:patient?.goals,interests:patient?.interests,sensory:patient?.sensory});setSuggestions(d.suggestions);setTab('Plan')}catch(e:any){setError(e.message)}}
async function createPatient(e:any){e.preventDefault();try{const p=await call('/patients',token,'POST',patientForm);setToast(`Patient account created: ${p.login.email} / ${p.login.password}`);setPatientForm({name:'',email:'',password:'',ageBand:'6–9',interests:'',communication:'',sensory:'',goals:''});setNewPatient(false);await loadDoctor();setPatient(p)}catch(e:any){setError(e.message)}}
async function assign(s:any){try{await call('/assignments',token,'POST',{patientId:patient.id,game:s.game,goal:s.goal,duration:10,schedule:'Daily · clinician assigned'});setToast(`${s.game} assigned to ${patient.name}`);loadDoctor()}catch(e:any){setError(e.message)}}
async function start(a:any){try{const s=await call('/sessions/start',token,'POST',{assignmentId:a.id});setSession(s);setPaused(false);setGame(a);setRemaining(s.limitSeconds||a.duration*60)}catch(e:any){setError(e.message)}}
async function setDemoTimer(enabled:boolean){try{const r=await call('/settings/demo-timer',token,'POST',{enabled});setDemo(r.demoTimer)}catch(e:any){setError(e.message)}}
async function togglePause(){if(!session)return;try{const r=await call(`/sessions/${session.id}/pause`,token,'POST',{paused:!paused});setPaused(r.paused)}catch(e:any){setError(e.message)}}
async function finish(status='completed',send=true){if(send&&session)try{await call(`/sessions/${session.id}/finish`,token,'POST',{status})}catch{}setSession(null);setGame(null);loadPatient()}
async function event(name:string){if(!session)return;try{await call(`/sessions/${session.id}/event`,token,'POST',{event:name});setToast('Nice work!')}catch(e:any){if(e.message.includes('Activity time'))finish('time_limit',false);else setError(e.message)}}
if(!user)return <main className="login-shell"><div className="login-art"><div className="brand">✿ neuplay</div><div className="doodle">☀️<br/><span>Small steps.<br/>Bright moments.</span><br/>🎨</div></div><form className="login-card" onSubmit={login}><span className="eyebrow">WELCOME TO NEUPLAY</span><h1>Welcome back</h1><p>Choose your login to continue.</p><div className="login-tabs"><button type="button" className={loginRole==='doctor'?'selected':''} onClick={()=>{setLoginRole('doctor');setEmail('doctor@neuplay.demo');setPassword('doctor123');setError('')}}>🩺 Doctor Login</button><button type="button" className={loginRole==='patient'?'selected':''} onClick={()=>{setLoginRole('patient');setEmail('patient@neuplay.demo');setPassword('patient123');setError('')}}>🌼 Patient Login</button></div><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary full">Sign in <span>→</span></button>{error&&<p className="error">{error}</p>}<div className="demo-box"><b>{loginRole==='doctor'?'Doctor demo login':'Patient demo login'}</b><br/>{email} / {password}<div className="quick"><span>Choose the other tab to switch login.</span></div></div><small>Prototype for learning and clinician-guided activity planning.</small></form></main>;
if(user.role==='doctor')return <div className="app"><aside className="sidebar"><div className="brand">✿ neuplay</div><div className="side-label">WORKSPACE</div>{['Overview','Patients','Plan','Sessions'].map(x=><button className={tab===x?'nav active':'nav'} onClick={()=>setTab(x)}>{x==='Overview'?'⌂':x==='Patients'?'♡':x==='Plan'?'✦':'◷'} &nbsp;{x}</button>)}<div className="side-bottom"><div className="avatar">AR</div><span><b>{user.name}</b><small>Doctor workspace</small></span><button onClick={logout}>↪</button></div></aside><main className="main"><header><div><div className="crumb">NEUPLAY / DOCTOR</div><h1>{tab==='Overview'?'Good day, Dr. Rao':tab}</h1></div><div className="head-right"><label className="demo-toggle"><input type="checkbox" checked={demo} onChange={e=>setDemoTimer(e.target.checked)}/> Quick timer demo</label><button className="avatar">AR</button></div></header>{error&&<div className="alert">{error}<button onClick={()=>setError('')}>×</button></div>}{toast&&<div className="toast" onClick={()=>setToast('')}>{toast}　×</div>}
{tab==='Overview'&&<><div className="welcome"><div><span className="eyebrow">YOUR WORKSPACE</span><h2>Care, made a little more playful.</h2><p>Review each person’s goals, shape a plan, and follow their activities here.</p><button className="primary" onClick={()=>setTab('Patients')}>View patients <span>→</span></button></div><div className="welcome-doodle">🌈<div>One step<br/>at a time</div></div></div><div className="stats"><div><span>MY PATIENTS</span><b>{patients.length}</b><small>Profiles in your care</small></div><div><span>ACTIVE PLANS</span><b>{patients.reduce((n,p)=>n+(p.assignments||[]).length,0)}</b><small>Clinician-assigned activities</small></div><div><span>RECENT SESSIONS</span><b>{patients.reduce((n,p)=>n+(p.sessions||[]).length,0)}</b><small>Activity records</small></div></div><Section title="Patient overview" action="See all" onAction={()=>setTab('Patients')}/><PatientList patients={patients} onSelect={(p:any)=>{setPatient(p);setTab('Patients')}}/></>}
{tab==='Patients'&&<><div className="patients-toolbar"><p>Create a patient profile and login, then build a plan from the same workspace.</p><button className="primary" onClick={()=>setNewPatient(!newPatient)}>{newPatient?'Close':'＋ New patient'}</button></div>{newPatient&&<form className="panel patient-create" onSubmit={createPatient}><h2>Create patient account</h2><div className="form-grid">{[['name','Preferred name'],['email','Login email'],['password','Temporary password'],['ageBand','Age band'],['interests','Interests'],['communication','Communication preferences'],['sensory','Sensory preferences'],['goals','Goals']].map(([k,label])=><label>{label}<input required={['name','email','password'].includes(k)} type={k==='password'?'password':'text'} value={patientForm[k]} onChange={e=>setPatientForm({...patientForm,[k]:e.target.value})}/></label>)}</div><button className="primary">Create login and profile</button></form>}<div className="two-col"><section className="panel"><Section title="People in your care"/><PatientList patients={patients} onSelect={setPatient} selected={patient?.id}/></section><section className="panel profile"><div className="profile-top"><div className="avatar big">{patient?.name?.slice(0,1)||'P'}</div><div><span className="eyebrow">PATIENT PROFILE</span><h2>{patient?.name||'Select a patient'}</h2><span>{patient?.ageBand} years · Individual support plan</span></div><button className="secondary" onClick={loadDoctor}>↻ Refresh</button></div><div className="info-grid"><Info title="Interests" value={patient?.interests}/><Info title="Communication" value={patient?.communication}/><Info title="Sensory preferences" value={patient?.sensory}/><Info title="Current goals" value={patient?.goals}/></div><div className="plan-action"><div><h3>AI planning assistant</h3><p>Get draft game ideas based on this profile. You review and assign them.</p></div><button className="primary" onClick={getSuggestions}>Suggest activities ✦</button></div><Section title="Assigned activities"/><AssignmentCards items={patient?.assignments||[]}/><Section title="Session history"/><SessionHistory items={patient?.sessions||[]}/></section></div></>}
{tab==='Plan'&&<><div className="banner-note">✦ Demo suggestions for clinician review. The assistant does not diagnose or prescribe.</div><div className="plan-head"><div><h2>Build a support plan</h2><p>Suggestions for {patient?.name||'your selected patient'}. Choose and assign what fits.</p></div><select value={patient?.id||''} onChange={e=>setPatient(patients.find(p=>p.id===e.target.value))}>{patients.map(p=><option value={p.id}>{p.name}</option>)}</select></div><button className="secondary" onClick={getSuggestions}>↻ Refresh suggestions</button><div className="suggest-grid">{(suggestions.length?suggestions:games.map(game=>({game,goal:'Choose a patient and request suggestions',why:'Suggestions are tailored to the selected profile.',adjustment:'Use the patient’s preferred settings.'}))).map((s:any,i:number)=><div className="suggest-card"><div className="game-emoji">{['💬','📖','🧩','🌈'][games.indexOf(s.game)]}</div><span className="eyebrow">SUGGESTION {i+1}</span><h3>{s.game}</h3><b>Possible goal</b><p>{s.goal}</p><b>Why it may fit</b><p>{s.why}</p><b>Accessibility idea</b><p>{s.adjustment}</p><button className="primary full" onClick={()=>assign(s)}>Assign to {patient?.name||'patient'} →</button></div>)}</div></>}
{tab==='Sessions'&&<><div className="panel"><Section title="Session monitoring"/><p className="muted">Session activity is shown when the patient is playing. Records are activity observations, not a diagnosis.</p>{patients.map((p:any)=><><h3>{p.name}</h3><SessionHistory items={p.sessions||[]}/></>)}</div></>}
</main></div>;
return <div className="patient-shell"><header className="patient-header"><div className="brand">✿ neuplay</div><div className="patient-right"><span>Hi, {user.name}!</span><button className="avatar" onClick={logout}>↪</button></div></header>{error&&<div className="alert">{error}<button onClick={()=>setError('')}>×</button></div>}{session?<GameRoom game={game} remaining={remaining} onEvent={event} onFinish={()=>finish('completed')} onPause={togglePause} paused={paused} toast={toast} demo={demo}/>:<main className="patient-main"><div className="today-banner"><span className="eyebrow">YOUR DAY, YOUR WAY</span><h1>What shall we explore today?</h1><p>Your activities are ready whenever you are.</p><div className="sunflower">🌼</div></div><div className="time-setting"><span>⏱ Activities have a time limit set by your doctor.</span><span>{demo?'Quick demo timer: 1 minute':'Standard assigned duration'}</span></div><h2>Today’s activities</h2>{assignments.length===0?<div className="empty">No activities scheduled right now. You can check back later.</div>:<div className="patient-games">{assignments.map((a:any,i:number)=><div className="patient-game"><div className="game-emoji">{['💬','📖','🧩','🌈'][games.indexOf(a.game)]||'🎨'}</div><div className="game-copy"><span className="eyebrow">ACTIVITY {i+1} · {a.duration} MIN</span><h3>{a.game}</h3><p>{gameDescription(a.game)}</p><small>{a.schedule}</small></div><button className="primary" onClick={()=>start(a)}>Play game <span>→</span></button></div>)}</div>}<p className="patient-foot">You can pause or stop whenever you need. Your doctor can see your activity record.</p></main>}</div>}
function gameDescription(name:string){const d:any={'Communication Choices':'Pick a picture or words to tell what you want.','Story Builder':'Help put three pictures in story order.','Daily Steps':'Put the hand-washing pictures in order.','Feelings Explorer':'Look at a story and choose how someone might feel.'};return d[name]||'Play a short activity chosen for you.'}
function Section({title,action,onAction}:any){return <div className="section-head"><h2>{title}</h2>{action&&<button onClick={onAction}>{action} →</button>}</div>}
function Info({title,value}:any){return <div className="info"><span>{title}</span><b>{value||'Not added yet'}</b></div>}
function PatientList({patients,onSelect,selected}:any){return <div className="patient-list">{patients.map((p:any)=><button className={`patient-row ${selected===p.id?'selected':''}`} onClick={()=>onSelect(p)}><div className="avatar">{p.name.slice(0,1)}</div><span><b>{p.name}</b><small>{p.ageBand} years · {p.assignments?.length||0} activities</small></span><span className="row-arrow">→</span></button>)}</div>}
function AssignmentCards({items}:any){return items.length?<div className="assigned-list">{items.map((a:any)=><div className="assigned"><span className="game-emoji">🎨</span><span><b>{a.game}</b><small>{a.goal}</small></span><span className="pill">{a.duration} min</span></div>)}</div>:<p className="muted">No activities assigned yet.</p>}
function SessionHistory({items}:any){return items.length?<div className="history">{items.slice().reverse().map((s:any)=><div><span className="dot"/><b>{s.status==='time_limit'?'Time limit reached':s.status==='completed'?'Completed':'Stopped'}</b><small>{new Date(s.startedAt).toLocaleString()} · {Math.ceil((s.seconds||0)/60)} min</small></div>)}</div>:<p className="muted">No sessions recorded yet.</p>}
function GameRoom({game,remaining,onEvent,onFinish,onPause,paused,toast,demo}:any){
 const [step,setStep]=useState(0),[choice,setChoice]=useState(''),[message,setMessage]=useState(''),[order,setOrder]=useState<string[]>([]);
 const mins=Math.floor(remaining/60),secs=remaining%60;
 const storyCards=['🐦 The bird finds a seed','🌱 The seed starts to grow','🌼 A flower blooms'];
 const routineCards=['🧼 Put soap on hands','💧 Rinse hands with water','🧻 Dry hands'];
 const prompts=game.game==='Communication Choices'?[{q:'You feel thirsty. What can you say?',opts:['🥤 I want a drink','🙋 Help me please','⏸ I need a break']},{q:'You need help with a toy. What can you say?',opts:['🙋 Help me please','🎨 I choose this','🥤 I want a drink']},{q:'You want to pause. What can you say?',opts:['⏸ I need a break','🙋 Help me please','🎨 I choose this']}]:[{q:'A block tower falls down. How might Sam feel?',opts:['😊 Happy','😟 Sad','😮 Surprised','🤔 Not sure']},{q:'Sam sees a friend at the park. How might Sam feel?',opts:['😊 Happy','😟 Worried','😮 Surprised','🤔 Not sure']},{q:'Rain stops a game outside. How might Sam feel?',opts:['😟 Disappointed','😊 Okay','😮 Surprised','🤔 Not sure']}];
 const isSort=game.game==='Story Builder'||game.game==='Daily Steps';
 const baseCards=game.game==='Story Builder'?storyCards:routineCards;
 useEffect(()=>{setOrder(game.game==='Daily Steps'?[routineCards[1],routineCards[0],routineCards[2]]:[storyCards[2],storyCards[0],storyCards[1]])},[game.game]);
 const instruction=game.game==='Story Builder'?'Put the pictures in order: first, next, last.':game.game==='Daily Steps'?'Put the hand-washing pictures in order.':game.game==='Feelings Explorer'?'Look at the story. Choose how Sam might feel. There can be many answers.':'Choose the words or picture that tell what you need.';
 function listen(){if(!('speechSynthesis'in window)){setMessage('Audio reading is not available in this browser.');return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(`Hi! Let's play ${game.game}. ${instruction}`);u.rate=.82;u.pitch=1.05;window.speechSynthesis.speak(u)}
 function moveCard(i:number,delta:number){const j=i+delta;if(j<0||j>=order.length)return;const n=[...order];[n[i],n[j]]=[n[j],n[i]];setOrder(n);setMessage('')}
 function advance(){if(isSort){const target=game.game==='Story Builder'?storyCards:routineCards;const ok=order.every((x,i)=>x===target[i]);onEvent('checked picture order');if(ok){setMessage('You did it! Your pictures are in order. 🌟');setTimeout(()=>onFinish(),900)}else setMessage('Good try! Look at the pictures and try moving them again.')}else if(!choice){setMessage('Choose one picture first. You can also choose “Not sure”.')}else{onEvent('made a choice');if(step>=2)onFinish();else{setStep(step+1);setChoice('');setMessage('Nice choosing! Let’s try one more. ✨')}}}
 return <div className="game-room"><header className="patient-header"><div className="brand">✿ neuplay</div><span className="timer">⏱ {String(mins).padStart(2,'0')}:{String(secs).padStart(2,'0')} left {demo&&<small> · demo</small>}</span><button className="secondary" onClick={onPause}>{paused?'Resume':'Pause'}</button><button className="secondary" onClick={onFinish}>Stop</button></header><main className="game-content">{paused&&<div className="paused-banner">⏸ Game paused. Your timer is paused too.</div>}<div className="game-title"><span className="game-emoji">{['💬','📖','🧩','🌈'][games.indexOf(game.game)]||'🎨'}</span><span className="eyebrow">{game.game}</span><span className="step-count">{isSort?'Picture game':`Step ${step+1} of 3`}</span></div>{remaining<=30&&!paused&&<div className="paused-banner">Your game will finish in {remaining} seconds.</div>}<h1>{isSort?(game.game==='Story Builder'?'Help the bird tell its story!':'Let’s wash our hands!'):game.game==='Feelings Explorer'?prompts[step].q:prompts[step].q}</h1><p className="game-instruction">{instruction}</p><button className="listen-button" onClick={listen} disabled={paused}>🔊 Listen to the instructions</button>
 {isSort?<div className="sort-area">{order.map((card:string,i:number)=><div className="sort-card"><span className="number-bubble">{i+1}</span><span>{card}</span><div className="move-buttons"><button disabled={paused||i===0} aria-label="Move picture up" onClick={()=>moveCard(i,-1)}>↑</button><button disabled={paused||i===order.length-1} aria-label="Move picture down" onClick={()=>moveCard(i,1)}>↓</button></div></div>)}<div className="sort-hint">Tap the arrows to move a picture. Put the pictures in order.</div></div>:<div className="choice-grid kid-choices">{prompts[step].opts.map((x:string)=><button disabled={paused} className={`choice ${choice===x?'chosen':''}`} onClick={()=>{setChoice(x);setMessage('')}}>{x}</button>)}</div>}
 {message&&<div className="game-message" role="status">{message}</div>}<div className="game-actions"><button disabled={paused} className="secondary" onClick={()=>{onEvent('help requested');setMessage('That’s okay. Take your time, or ask your grown-up for help.')}}>🙋 I need help</button><button disabled={paused} className="primary" onClick={advance}>{isSort?'Check my pictures':'Next'} <span>→</span></button></div><p className="muted">You can pause or stop whenever you need.</p>{toast&&<div className="toast">{toast}</div>}</main></div>
}
