import express from 'express'; import cors from 'cors'; import jwt from 'jsonwebtoken'; import fs from 'node:fs'; import path from 'node:path';
const app=express(); app.use(cors({origin:'http://localhost:5173'})); app.use(express.json());
const PORT=3001, SECRET=process.env.JWT_SECRET||'local-demo-secret-change-me', DATA=path.join(process.cwd(),'server','data.json');
type User={id:string,name:string,email:string,password:string,role:'doctor'|'patient'};
type Assignment={id:string,patientId:string,game:string,goal:string,duration:number,demoDuration:number,schedule:string,status:string,createdAt:string,nextAllowedAt?:number};
type Session={id:string,assignmentId:string,patientId:string,startedAt:number,endedAt?:number,seconds:number,status:string,events:string[],pausedAt?:number,pausedTotal?:number};
type DB={users:User[],patients:any[],assignments:Assignment[],sessions:Session[],demoTimer?:boolean};
const seed:DB={users:[{id:'d1',name:'Dr. Asha Rao',email:'doctor@neuplay.demo',password:'doctor123',role:'doctor'},{id:'p1',name:'Aarav',email:'patient@neuplay.demo',password:'patient123',role:'patient'}],patients:[{id:'p1',name:'Aarav',ageBand:'6–9',interests:'space, animals, drawing',communication:'Pictures and short phrases',sensory:'Low sound, gentle animation',goals:'Make choices; practice sequencing'}],assignments:[{id:'a1',patientId:'p1',game:'Communication Choices',goal:'Practice choosing and expressing a request',duration:10,demoDuration:1,schedule:'Daily · 4:00 PM',status:'active',createdAt:new Date().toISOString()},{id:'a2',patientId:'p1',game:'Story Builder',goal:'Practice putting a short story in order',duration:10,demoDuration:1,schedule:'Daily · 4:00 PM',status:'active',createdAt:new Date().toISOString()},{id:'a3',patientId:'p1',game:'Daily Steps',goal:'Practice ordering steps in a familiar routine',duration:10,demoDuration:1,schedule:'Daily · 4:00 PM',status:'active',createdAt:new Date().toISOString()},{id:'a4',patientId:'p1',game:'Feelings Explorer',goal:'Explore feelings in simple stories',duration:10,demoDuration:1,schedule:'Daily · 4:00 PM',status:'active',createdAt:new Date().toISOString()}],sessions:[],demoTimer:false};
let db:DB; try{db=JSON.parse(fs.readFileSync(DATA,'utf8'))}catch{db=seed;fs.writeFileSync(DATA,JSON.stringify(db,null,2))} function save(){fs.writeFileSync(DATA,JSON.stringify(db,null,2))} function elapsed(s:Session,now=Date.now()){return Math.max(0,Math.floor(((s.pausedAt||now)-s.startedAt-(s.pausedTotal||0))/1000))}
function auth(req:any,res:any,next:any){const h=req.headers.authorization||'';try{req.user=jwt.verify(h.replace(/^Bearer /,''),SECRET);next()}catch{return res.status(401).json({error:'Please sign in again.'})}}
function role(wanted:string){return (req:any,res:any,next:any)=>req.user?.role===wanted?next():res.status(403).json({error:'Not allowed'})}
app.post('/api/login',(req,res)=>{const {email,password}=req.body||{};const u=db.users.find(x=>x.email.toLowerCase()===String(email).toLowerCase()&&x.password===password);if(!u)return res.status(401).json({error:'Email or password did not match.'});const token=jwt.sign({id:u.id,name:u.name,role:u.role},SECRET,{expiresIn:'12h'});res.json({token,user:{id:u.id,name:u.name,role:u.role}})});
app.post('/api/patients',auth,role('doctor'),(req:any,res)=>{const {name,email,password,ageBand='6–9',interests='',communication='',sensory='',goals=''}=req.body||{};if(!name||!email||!password||String(password).length<6)return res.status(400).json({error:'Name, email, and a password of at least 6 characters are required.'});if(db.users.some(u=>u.email.toLowerCase()===String(email).toLowerCase()))return res.status(409).json({error:'That email is already in use.'});const id='p'+Date.now();db.users.push({id,name,email,password,role:'patient'});const p={id,name,ageBand,interests,communication,sensory,goals};db.patients.push(p);save();res.json({...p,login:{email,password}})});
app.get('/api/settings',auth,(_req,res)=>res.json({demoTimer:!!db.demoTimer}));
app.post('/api/settings/demo-timer',auth,role('doctor'),(req,res)=>{db.demoTimer=!!req.body?.enabled;save();res.json({demoTimer:db.demoTimer})});
app.get('/api/patients',auth,role('doctor'),(_req,res)=>res.json(db.patients.map(p=>({...p,assignments:db.assignments.filter(a=>a.patientId===p.id),sessions:db.sessions.filter(s=>s.patientId===p.id)}))));
app.get('/api/my-assignments',auth,role('patient'),(req:any,res)=>res.json({items:db.assignments.filter(a=>a.patientId===req.user.id&&a.status==='active'&&(!a.nextAllowedAt||Date.now()>=a.nextAllowedAt)),demoTimer:!!db.demoTimer}));
app.post('/api/suggest',auth,role('doctor'),(req,res)=>{const {goals='',interests='',sensory=''}=req.body||{};const all=[{game:'Communication Choices',goal:'Practice expressing a choice or request',why:`Can use interests such as ${interests||'preferred topics'} with picture or phrase choices.`,adjustment:sensory||'Offer picture choices and keep sound low.'},{game:'Story Builder',goal:'Practice sequencing and exploring a character’s next step',why:`Builds a short story around ${interests||'a preferred topic'}.`,adjustment:'Use 3–4 picture cards and allow multiple answers.'},{game:'Daily Steps',goal:'Practice ordering steps in a familiar routine',why:`Can connect with the goal: ${goals||'a selected daily routine'}.`,adjustment:'Use familiar pictures, one step per screen.'},{game:'Feelings Explorer',goal:'Explore possible feelings in a story',why:'Supports naming or discussing feelings without requiring one correct answer.',adjustment:'Include “not sure” and allow skipping.'}];res.json({notice:'Demo suggestions for doctor review. These are not medical advice.',suggestions:all})});
app.post('/api/assignments',auth,role('doctor'),(req,res)=>{const {patientId,game,goal,duration,schedule}=req.body||{};if(!db.patients.some(p=>p.id===patientId)||!game||!goal||!Number.isFinite(Number(duration))||Number(duration)<1||Number(duration)>60)return res.status(400).json({error:'Check patient, game, goal, and a duration from 1 to 60 minutes.'});const a:Assignment={id:'a'+Date.now(),patientId,game,goal,duration:Number(duration),demoDuration:1,schedule:schedule||'Daily',status:'active',createdAt:new Date().toISOString()};db.assignments.push(a);save();res.json(a)});
app.post('/api/sessions/start',auth,role('patient'),(req:any,res)=>{const {assignmentId,demo}=req.body||{};const a=db.assignments.find(x=>x.id===assignmentId&&x.patientId===req.user.id&&x.status==='active');if(!a)return res.status(404).json({error:'Assignment not available.'});const now=Date.now();if(a.nextAllowedAt&&now<a.nextAllowedAt)return res.status(403).json({error:'This activity is finished for now. Please check your schedule.'});const live=db.sessions.find(s=>s.assignmentId===a.id&&!s.endedAt);if(live)return res.json(live);const s:Session={id:'s'+now,assignmentId:a.id,patientId:req.user.id,startedAt:now,seconds:0,status:'active',events:[],pausedTotal:0};(s as any).limitSeconds=(db.demoTimer?Math.min(60,a.demoDuration*60):a.duration*60);db.sessions.push(s);save();res.json({...s,limitSeconds:(s as any).limitSeconds})});
app.post('/api/sessions/:id/event',auth,role('patient'),(req:any,res)=>{const s=db.sessions.find(x=>x.id===req.params.id&&x.patientId===req.user.id&&!x.endedAt);if(!s)return res.status(404).json({error:'Session not active.'});const a=db.assignments.find(x=>x.id===s.assignmentId)!;const limit=(s as any).limitSeconds||a.duration*60;if(s.pausedAt)return res.status(409).json({error:'Resume the activity to continue.'});if(elapsed(s)>=limit){s.endedAt=Date.now();s.seconds=limit;s.status='time_limit';a.nextAllowedAt=Date.now()+20*60*60*1000;save();return res.status(403).json({expired:true,error:'Activity time is finished.'})}const ev=String(req.body?.event||'activity');s.events.push(ev);save();res.json({ok:true,remaining:Math.max(0,limit-elapsed(s))})});
app.post('/api/sessions/:id/finish',auth,role('patient'),(req:any,res)=>{const s=db.sessions.find(x=>x.id===req.params.id&&x.patientId===req.user.id&&!x.endedAt);if(!s)return res.status(404).json({error:'Session not active.'});const a=db.assignments.find(x=>x.id===s.assignmentId)!;const limit=(s as any).limitSeconds||a.duration*60;s.seconds=Math.min(limit,elapsed(s));s.endedAt=Date.now();s.status=String(req.body?.status||'completed');a.nextAllowedAt=Date.now()+20*60*60*1000;save();res.json(s)});
app.post('/api/sessions/:id/pause',auth,role('patient'),(req:any,res)=>{const s=db.sessions.find(x=>x.id===req.params.id&&x.patientId===req.user.id&&!x.endedAt);if(!s)return res.status(404).json({error:'Session not active.'});const now=Date.now();if(req.body?.paused&&!s.pausedAt)s.pausedAt=now;else if(!req.body?.paused&&s.pausedAt){s.pausedTotal=(s.pausedTotal||0)+(now-s.pausedAt);s.pausedAt=undefined}save();res.json({paused:!!s.pausedAt})});
app.get('/api/sessions/:id/status',auth,role('patient'),(req:any,res)=>{const s=db.sessions.find(x=>x.id===req.params.id&&x.patientId===req.user.id);if(!s)return res.status(404).json({error:'Session not found.'});const a=db.assignments.find(x=>x.id===s.assignmentId)!;const limit=(s as any).limitSeconds||a.duration*60;const remaining=Math.max(0,limit-elapsed(s));if(remaining===0&&!s.endedAt){s.endedAt=Date.now();s.seconds=limit;s.status='time_limit';a.nextAllowedAt=Date.now()+20*60*60*1000;save()}res.json({remaining,expired:remaining===0,session:s,assignment:a})});
app.listen(PORT,()=>console.log(`Neuplay API running at http://localhost:${PORT}`));
